name: Run Python Script and Auto Release

on:
  # Trigger the workflow on both push and pull request
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  # Run tests when PRs target main branch
    types: [opened, synchronize, reopened]  # Optional: specific PR events

permissions:
  contents: write

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Generate requirements.txt if not found
      - name: Generate requirements.txt if missing
        run: |
          if [ ! -f requirements.txt ]; then
            echo "⚙️ No requirements.txt found — creating a default one..."
            echo "numpy" >> requirements.txt
            echo "pytest" >> requirements.txt
          else
            echo "✅ Found existing requirements.txt"
          fi
          cat requirements.txt
          
      # Step 4: Install dependencies
      - name: Environment setup
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run tests (fail workflow if any test fails)
      - name: Run tests
        run: pytest -v

      # Step 6: Run main.py only if all tests pass
      - name: Execute main.py
        if: ${{ success() }}
        run: python main.py

  release:
    needs: run-python
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1: Get the latest tag and increment version
      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          latest_tag_number=${latest_tag#v}
          IFS='.' read -r major minor patch <<< "$latest_tag_number"
          patch=$((patch + 1))
          new_tag="v${major}.${minor}.${patch}"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
          echo "Next version: $new_tag"

      # Step 2: Create a GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.new_tag }}
          name: "Release ${{ steps.get_tag.outputs.new_tag }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.MY_CUSTOM_TOKEN }}
