name: Run Python Script

on:
  push:                # Runs on every push
  pull_request:        # Also runs for pull requests

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Run your main.py script
      - name: Execute main.py if exists
        run: |
          if [ -f main.py ]; then
            echo "Found main.py — running it now..."
            python main.py
          else
            echo "⚠️ main.py not found, skipping execution."
          fi

      # Step 4: Optional - Confirm success
      - name: Success message
        if: ${{ success() }}
        run: echo "✅ main.py executed successfully!"
